import './globals.css'
import type { Metadata } from 'next'
import { Barlow_Semi_Condensed } from 'next/font/google'
import { ReactNode } from "react";

const barlow = Barlow_Semi_Condensed({ weight: ['400', '500', '600'], subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={barlow.className}>{children}</body>
    </html>
  );
}
